# Generated by Django 4.2.5 on 2023-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
