# Generated by Django 4.2.5 on 2023-09-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="website_url",
            new_name="website",
        ),
    ]
