# Generated by Django 4.2.5 on 2023-09-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_expense_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="total_amount",
            new_name="initial_amount",
        ),
    ]
