# Generated by Django 4.2.5 on 2023-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_expense_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WK", "Weekly"),
                    ("BW", "Bi-weekly"),
                    ("MN", "Monthly"),
                    ("QR", "Quarterly"),
                    ("YR", "Yearly"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="next_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
