# Generated by Django 4.2.5 on 2023-09-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_bill"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="amount",
            new_name="amount_due",
        ),
        migrations.AddField(
            model_name="bill",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bill",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
